// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odzaacarlkmxqrpmggwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kemFhY2FybGtteHFycG1nZ3dlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNTE2NTAsImV4cCI6MjA1OTgyNzY1MH0.eBvzqqY9T2Kzvw0BA7yTwTiedjslyI5rLzc9DotbpGg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
