import { MetaQube } from '@/lib/types';

export const qubeData = {
  monDai: {
    "iQube-Identifier": "Qrypto Persona iQube",
    "iQube-Type": "DataQube",
    "iQube-Designer": "Aigent MonDAI",
    "iQube-Use": "For personalized cryptocurrency recommendations and portfolio analysis",
    "Owner-Type": "Person",
    "Owner-Identifiability": "Semi-Identifiable",
    "Date-Minted": new Date().toISOString(),
    "Related-iQubes": ["MetisQube", "VeniceQube", "WalletQube"],
    "X-of-Y": "1 of 5",
    "Sensitivity-Score": 6,
    "Verifiability-Score": 7,
    "Accuracy-Score": 8,
    "Risk-Score": 5
  },
  
  knytPersona: {
    "iQube-Identifier": "KNYT Persona iQube",
    "iQube-Type": "DataQube",
    "iQube-Designer": "KNYT Ecosystem",
    "iQube-Use": "For KNYT ecosystem profile management and reward tracking",
    "Owner-Type": "Person",
    "Owner-Identifiability": "Semi-Identifiable",
    "Date-Minted": new Date().toISOString(),
    "Related-iQubes": ["QryptoPersona", "MetisQube", "EcosystemQube"],
    "X-of-Y": "1 of 3",
    "Sensitivity-Score": 7,
    "Verifiability-Score": 8,
    "Accuracy-Score": 8,
    "Risk-Score": 6.5
  },

  metis: {
    "iQube-Identifier": "Metis iQube",
    "iQube-Type": "AgentQube",
    "iQube-Designer": "Aigent Metis",
    "iQube-Use": "For risk evaluation of wallets and tokens",
    "Owner-Type": "Algorithm",
    "Owner-Identifiability": "Non-Identifiable",
    "Date-Minted": new Date().toISOString(),
    "Related-iQubes": ["WalletQube", "TokenQube", "SecurityQube"],
    "X-of-Y": "3 of 10",
    "Sensitivity-Score": 3,
    "Verifiability-Score": 9,
    "Accuracy-Score": 7,
    "Risk-Score": 2
  },
  venice: {
    "iQube-Identifier": "Venice iQube",
    "iQube-Type": "ModelQube",
    "iQube-Designer": "Aigent Venice",
    "iQube-Use": "For privacy-preserving AI model services",
    "Owner-Type": "Algorithm",
    "Owner-Identifiability": "Non-Identifiable",
    "Date-Minted": new Date().toISOString(),
    "Related-iQubes": ["PrivacyQube", "AIModelQube", "DataProtectionQube"],
    "X-of-Y": "2 of 7",
    "Sensitivity-Score": 5,
    "Verifiability-Score": 8,
    "Accuracy-Score": 7,
    "Risk-Score": 2
  },
  openai: {
    "iQube-Identifier": "OpenAI iQube",
    "iQube-Type": "ModelQube",
    "iQube-Designer": "OpenAI",
    "iQube-Use": "For advanced language model services and AI capabilities",
    "Owner-Type": "Algorithm",
    "Owner-Identifiability": "Non-Identifiable",
    "Date-Minted": new Date().toISOString(),
    "Related-iQubes": ["AIModelQube", "LanguageQube", "ReasoningQube"],
    "X-of-Y": "3 of 7",
    "Sensitivity-Score": 7,
    "Verifiability-Score": 5,
    "Accuracy-Score": 7,
    "Risk-Score": 7
  },
  chainGPT: {
    "iQube-Identifier": "ChainGPT",
    "iQube-Type": "ModelQube",
    "iQube-Designer": "ChainGPT Labs",
    "iQube-Use": "Crypto-native AI specialized for blockchain, DeFi, and smart contract development",
    "Interoperability-Score": 9.0,
    "Accessibility-Score": 8.5,
    "Security-Score": 9.3,
    "Privacy-Score": 8.8,
    "Efficiency-Score": 9.2,
    "Innovation-Score": 9.5,
    "Cost-Effectiveness-Score": 8.7,
    "Reliability-Score": 9.1,
    "User-Experience-Score": 8.9,
    "Community-Adoption-Score": 8.6,
    "Total-iQube-Score": 89.6,
    "Related-iQubes": ["Qrypto Persona", "KNYT Persona", "TokenQube", "Venice"]
  },
  gdrive: {
    "iQube-Identifier": "GDrive iQube",
    "iQube-Type": "DataQube",
    "iQube-Designer": "Aigent GDrive",
    "iQube-Use": "For accessing and managing personal data in Google Drive",
    "Owner-Type": "Person",
    "Owner-Identifiability": "Identifiable",
    "Date-Minted": new Date().toISOString(),
    "Related-iQubes": ["PersonalDataQube", "CloudStorageQube", "DocumentQube"],
    "X-of-Y": "4 of 12",
    "Sensitivity-Score": 8,
    "Verifiability-Score": 5,
    "Accuracy-Score": 6,
    "Risk-Score": 7
  },
  content: {
    "iQube-Identifier": "Content iQube",
    "iQube-Type": "ToolQube",
    "iQube-Designer": "Aigent Content",
    "iQube-Use": "For creating and managing digital content",
    "Owner-Type": "Person",
    "Owner-Identifiability": "Semi-Identifiable",
    "Date-Minted": new Date().toISOString(),
    "Related-iQubes": ["DigitalContentQube", "MediaQube", "CreativeQube"],
    "X-of-Y": "6 of 15",
    "Sensitivity-Score": 5,
    "Verifiability-Score": 7,
    "Accuracy-Score": 7,
    "Risk-Score": 4
  },
  model: {
    "iQube-Identifier": "Model iQube",
    "iQube-Type": "ToolQube",
    "iQube-Designer": "Aigent Model",
    "iQube-Use": "For training and deploying AI models",
    "Owner-Type": "Algorithm",
    "Owner-Identifiability": "Non-Identifiable",
    "Date-Minted": new Date().toISOString(),
    "Related-iQubes": ["AIModelQube", "TrainingDataQube", "DeploymentQube"],
    "X-of-Y": "7 of 20",
    "Sensitivity-Score": 4,
    "Verifiability-Score": 8,
    "Accuracy-Score": 9,
    "Risk-Score": 3
  }
};

export const monDaiQubeData = {
  id: 'monDai',
  name: 'Qrypto Persona iQube',
  type: 'Personal Data',
  href: '/settings',
  active: true
};
