import { MetaQube } from '@/lib/types';

export const monDaiQubeData: MetaQube = {
  "iQube-Identifier": "Qrypto Persona iQube",
  "iQube-Type": "DataQube",
  "iQube-Designer": "Aigent MonDAI",
  "iQube-Use": "Personal cryptocurrency profile and preferences data",
  "Owner-Type": "Person",
  "Owner-Identifiability": "Semi-Identifiable",
  "Date-Minted": "2024-01-15",
  "Related-iQubes": ["VeniceQube", "MetisQube"],
  "X-of-Y": "1 of 6",
  "Description": "Personal cryptocurrency profile and preferences data",
  "Access-Control": "Private",
  "Encryption-Level": "AES-256",
  "Created": "2024-01-15",
  "Last-Updated": "2024-03-10",
  "Version": "1.2.0",
  "Size": "2.3 MB",
  "Status": "Active",
  "Network": "Ethereum",
  "Smart-Contract": "0x742d35Cc6532C4532F37cC",
  "IPFS-Hash": "QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco",
  "Sensitivity-Score": 5,
  "Verifiability-Score": 5,
  "Accuracy-Score": 5,
  "Risk-Score": 4
};

export const veniceQubeData: MetaQube = {
  "iQube-Identifier": "Venice iQube",
  "iQube-Type": "ModelQube",
  "iQube-Designer": "Aigent Venice",
  "iQube-Use": "AI model service that protects privacy and prevents censorship",
  "Owner-Type": "Person",
  "Owner-Identifiability": "Semi-Identifiable",
  "Date-Minted": "2024-02-01",
  "Related-iQubes": ["MonDAIQube", "MetisQube"],
  "X-of-Y": "2 of 6",
  "Description": "AI model service that protects privacy and prevents censorship",
  "Access-Control": "Private",
  "Encryption-Level": "AES-256",
  "Created": "2024-02-01",
  "Last-Updated": "2024-03-15",
  "Version": "1.1.0",
  "Size": "1.8 MB",
  "Status": "Active",
  "Network": "Ethereum",
  "Smart-Contract": "0x853d46Ee7643B5532F48dD",
  "IPFS-Hash": "QmYpqzjW4WknFiJnKLwHCnL73vedxjQkDDP1mXWo7vdp",
  "Sensitivity-Score": 2,
  "Verifiability-Score": 9,
  "Accuracy-Score": 8,
  "Risk-Score": 2
};

export const metisQubeData: MetaQube = {
  "iQube-Identifier": "Metis iQube",
  "iQube-Type": "AgentQube",
  "iQube-Designer": "Aigent Metis",
  "iQube-Use": "An algorithm that evaluates risks associated with wallets and tokens",
  "Owner-Type": "Person",
  "Owner-Identifiability": "Semi-Identifiable",
  "Date-Minted": "2024-01-20",
  "Related-iQubes": ["MonDAIQube", "VeniceQube"],
  "X-of-Y": "3 of 6",
  "Description": "An algorithm that evaluates risks associated with wallets and tokens",
  "Access-Control": "Private",
  "Encryption-Level": "AES-256",
  "Created": "2024-01-20",
  "Last-Updated": "2024-03-12",
  "Version": "1.3.0",
  "Size": "3.1 MB",
  "Status": "Active",
  "Network": "Ethereum",
  "Smart-Contract": "0x964e57Ff8754C6643G59eE",
  "IPFS-Hash": "QmZqrzkW5WknFiJnKLwHCnL74vedxjQkDDP1mXWo8wfq",
  "Sensitivity-Score": 2,
  "Verifiability-Score": 9,
  "Accuracy-Score": 8,
  "Risk-Score": 2
};

export const gdriveQubeData: MetaQube = {
  "iQube-Identifier": "GDrive iQube",
  "iQube-Type": "DataQube",
  "iQube-Designer": "Aigent GDrive",
  "iQube-Use": "Google Drive document and file storage integration",
  "Owner-Type": "Person",
  "Owner-Identifiability": "Semi-Identifiable",
  "Date-Minted": "2024-02-10",
  "Related-iQubes": ["MonDAIQube", "ContentQube"],
  "X-of-Y": "4 of 6",
  "Description": "Google Drive document and file storage integration",
  "Access-Control": "Private",
  "Encryption-Level": "AES-256",
  "Created": "2024-02-10",
  "Last-Updated": "2024-03-08",
  "Version": "1.0.5",
  "Size": "4.7 MB",
  "Status": "Inactive",
  "Network": "Ethereum",
  "Smart-Contract": "0xa75f48Gg9865D7754H60fF",
  "IPFS-Hash": "QmArszlW6WknFiJnKLwHCnL75vedxjQkDDP1mXWo9xgr",
  "Sensitivity-Score": 9.0,
  "Verifiability-Score": 8.8,
  "Accuracy-Score": 8.6,
  "Risk-Score": 1.8
};

export const contentQubeData: MetaQube = {
  "iQube-Identifier": "Content iQube",
  "iQube-Type": "DataQube",
  "iQube-Designer": "Aigent Content",
  "iQube-Use": "User-generated content and media storage",
  "Owner-Type": "Person",
  "Owner-Identifiability": "Semi-Identifiable",
  "Date-Minted": "2024-01-25",
  "Related-iQubes": ["MonDAIQube", "GDriveQube"],
  "X-of-Y": "5 of 6",
  "Description": "User-generated content and media storage",
  "Access-Control": "Private",
  "Encryption-Level": "AES-256",
  "Created": "2024-01-25",
  "Last-Updated": "2024-03-05",
  "Version": "1.1.2",
  "Size": "6.2 MB",
  "Status": "Active",
  "Network": "Ethereum",
  "Smart-Contract": "0xb86g59Hh0976E8865I71gG",
  "IPFS-Hash": "QmBstzmW7WknFiJnKLwHCnL76vedxjQkDDP1mXWo0yhs",
  "Sensitivity-Score": 7.5,
  "Verifiability-Score": 8.1,
  "Accuracy-Score": 8.3,
  "Risk-Score": 2.2
};

export const modelQubeData: MetaQube = {
  "iQube-Identifier": "Model iQube",
  "iQube-Type": "AgentQube",
  "iQube-Designer": "Aigent Model",
  "iQube-Use": "AI model configurations and training data",
  "Owner-Type": "Person",
  "Owner-Identifiability": "Semi-Identifiable",
  "Date-Minted": "2024-02-15",
  "Related-iQubes": ["MonDAIQube", "VeniceQube", "MetisQube"],
  "X-of-Y": "6 of 6",
  "Description": "AI model configurations and training data",
  "Access-Control": "Private",
  "Encryption-Level": "AES-256",
  "Created": "2024-02-15",
  "Last-Updated": "2024-03-20",
  "Version": "1.4.0",
  "Size": "8.9 MB",
  "Status": "Active",
  "Network": "Ethereum",
  "Smart-Contract": "0xc97h60Ii1087F9976J82hH",
  "IPFS-Hash": "QmCtuzlW8WknFiJnKLwHCnL77vedxjQkDDP1mXWo1zit",
  "Sensitivity-Score": 7.8,
  "Verifiability-Score": 8.9,
  "Accuracy-Score": 9.4,
  "Risk-Score": 1.9
};

export const knytPersonaQubeData: MetaQube = {
  "iQube-Identifier": "KNYT Persona iQube",
  "iQube-Type": "DataQube",
  "iQube-Designer": "Aigent KNYT",
  "iQube-Use": "KNYT ecosystem profile and digital asset management data with 2,800 Satoshi reward",
  "Owner-Type": "Person",
  "Owner-Identifiability": "Semi-Identifiable",
  "Date-Minted": "2024-03-01",
  "Related-iQubes": ["QryptoPersonaQube", "VeniceQube", "MetisQube"],
  "X-of-Y": "7 of 7",
  "Description": "KNYT ecosystem profile including OM membership, digital assets, and reward system (2,800 Satoshi = 2 $KNYT = $2.80)",
  "Access-Control": "Private",
  "Encryption-Level": "AES-256",
  "Created": "2024-03-01",
  "Last-Updated": "2024-03-01",
  "Version": "1.0.0",
  "Size": "3.2 MB",
  "Status": "Active",
  "Network": "Ethereum",
  "Smart-Contract": "0xd08i70Jj2198G0087K93iI",
  "IPFS-Hash": "QmEuvnmW9WknFiJnKLwHCnL78vedxjQkDDP1mXWo2ajv",
  "Sensitivity-Score": 6.5,
  "Verifiability-Score": 8.7,
  "Accuracy-Score": 8.9,
  "Risk-Score": 2.1
};

export const qubeData = {
  monDai: monDaiQubeData,
  venice: veniceQubeData,
  metis: metisQubeData,
  gdrive: gdriveQubeData,
  content: contentQubeData,
  model: modelQubeData,
  knytPersona: knytPersonaQubeData
};
